function esc(text = "") {
  return String(text)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/\r/g, "")
    .replace(/\n/g, " ");
}

function hexToRgb(hex = "#0f172a") {
  const cleaned = String(hex || "").replace(/[^0-9a-f]/gi, "");
  const full = cleaned.length === 3 ? cleaned.split("").map((x) => x + x).join("") : cleaned.padEnd(6, "0").slice(0, 6);
  const n = parseInt(full, 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

function wrapText(text = "", maxChars = 92) {
  const words = String(text || "").split(/\s+/).filter(Boolean);
  const lines = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxChars) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function buildStream(page, theme) {
  const cmds = [];
  const [r1, g1, b1] = hexToRgb(theme.header || "#0f172a");
  const [r2, g2, b2] = hexToRgb(theme.accent || "#2563eb");
  const [rf, gf, bf] = hexToRgb(theme.foreground || "#f8fafc");

  cmds.push(`q ${r1.toFixed(3)} ${g1.toFixed(3)} ${b1.toFixed(3)} rg 40 770 515 36 re f Q`);
  cmds.push(`BT /F2 18 Tf ${rf.toFixed(3)} ${gf.toFixed(3)} ${bf.toFixed(3)} rg 52 792 Td (${esc(page.title)}) Tj ET`);
  if (page.subtitle) cmds.push(`BT /F1 10 Tf 0.92 0.96 1 rg 52 776 Td (${esc(page.subtitle)}) Tj ET`);

  let y = 748;
  for (const line of page.lines) {
    if (line.type === "section") {
      cmds.push(`q ${r2.toFixed(3)} ${g2.toFixed(3)} ${b2.toFixed(3)} rg 40 ${y - 2} 515 18 re f Q`);
      cmds.push(`BT /F2 10 Tf 1 1 1 rg 48 ${y + 4} Td (${esc(line.text)}) Tj ET`);
      y -= 24;
      continue;
    }
    const size = line.size || 10;
    const isBold = line.bold ? "/F2" : "/F1";
    const [tr, tg, tb] = hexToRgb(line.color || theme.text || "#111827");
    cmds.push(`BT ${isBold} ${size} Tf ${tr.toFixed(3)} ${tg.toFixed(3)} ${tb.toFixed(3)} rg 48 ${y} Td (${esc(line.text)}) Tj ET`);
    y -= line.gap || 14;
  }

  cmds.push(`BT /F1 9 Tf 0.45 0.49 0.55 rg 40 26 Td (${esc(theme.footer || "Generated by Pocket Money admin")}) Tj ET`);
  const body = cmds.join("\n");
  return `${body}`;
}

export function buildPdfBuffer({ title = "Document", subtitle = "", sections = [], theme = {} }) {
  const headerTheme = {
    header: theme.header || "#0f172a",
    accent: theme.accent || "#2563eb",
    foreground: theme.foreground || "#f8fafc",
    text: theme.text || "#111827",
    footer: theme.footer || "Pocket Money Document",
  };

  const lines = [];
  for (const section of sections) {
    if (section.heading) lines.push({ type: "section", text: section.heading });
    for (const item of section.lines || []) {
      if (typeof item === "string") {
        wrapText(item).forEach((text) => lines.push({ text }));
      } else if (item && typeof item === "object") {
        const wrapped = wrapText(item.text || "", item.maxChars || 92);
        wrapped.forEach((text, idx) => lines.push({ ...item, text, bold: idx === 0 ? item.bold : false }));
      }
    }
  }

  const pages = [];
  let current = { title, subtitle, lines: [] };
  let used = 0;
  for (const line of lines) {
    const cost = line.type === "section" ? 24 : (line.gap || 14);
    if (used + cost > 690 && current.lines.length) {
      pages.push(current);
      current = { title, subtitle, lines: [] };
      used = 0;
    }
    current.lines.push(line);
    used += cost;
  }
  pages.push(current);

  const objects = [];
  const addObject = (content) => {
    objects.push(content);
    return objects.length;
  };

  const font1 = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const font2 = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  const pageRefs = [];
  for (const page of pages) {
    const stream = buildStream(page, headerTheme);
    const contentRef = addObject(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    const pageRef = addObject(`<< /Type /Page /Parent 0 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${contentRef} 0 R >>`);
    pageRefs.push(pageRef);
  }

  const pagesRef = addObject(`<< /Type /Pages /Kids [${pageRefs.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageRefs.length} >>`);
  for (const pageRef of pageRefs) {
    objects[pageRef - 1] = objects[pageRef - 1].replace("/Parent 0 0 R", `/Parent ${pagesRef} 0 R`);
  }
  const catalogRef = addObject(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((obj, idx) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${idx + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefPos = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogRef} 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
